export * from './aboutus/aboutus.component';
export * from './delivery-information/delivery-information.component';
export * from './privacy-policy/privacy-policy.component';
export * from './return-policy/return-policy.component';
export * from './terms-condition/terms-condition.component';
export * from './contact-us/contact-us.component';
export * from './faq/faq.component';
export * from './blog/blog.component';
export * from './blog-detail/blog-detail.component';